//! Shared benchmark configuration for the **awesome-pq-signatures** workspace.
//!
//! All DSA crates sign the same canonical 32-byte message so that
//! benchmark results are directly comparable.  The message is the
//! SHA-256 hash of a human-readable string defined in the workspace-level
//! [`bench_config.toml`] file.
//!
//! # Usage
//!
//! ```rust,ignore
//! use pq_bench::{BENCH_MESSAGE, BENCH_SECURITY_TARGET, BENCH_STATEFUL_CAPACITY_CLASS};
//!
//! // 32-byte SHA-256 digest — pass this to sign / verify.
//! assert_eq!(BENCH_MESSAGE.len(), 32);
//! assert!(matches!(BENCH_SECURITY_TARGET, "level1" | "level3"));
//! assert!(matches!(BENCH_STATEFUL_CAPACITY_CLASS, "pow2_10" | "pow2_20"));
//! ```

// Pull in the constant generated by build.rs from bench_config.toml.
include!(concat!(env!("OUT_DIR"), "/bench_config.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bench_message_is_32_bytes() {
        assert_eq!(BENCH_MESSAGE.len(), 32);
    }

    #[test]
    fn bench_message_is_not_all_zeros() {
        assert_ne!(BENCH_MESSAGE, [0u8; 32]);
    }

    #[test]
    fn benchmark_security_target_is_supported() {
        assert!(matches!(BENCH_SECURITY_TARGET, "level1" | "level3"));
    }

    #[test]
    fn benchmark_stateful_capacity_class_is_supported() {
        assert!(matches!(
            BENCH_STATEFUL_CAPACITY_CLASS,
            "pow2_10" | "pow2_20"
        ));
    }
}
