[workspace]
members = [
    "crates/pq_bench",
    "crates/falcon",
    "crates/dilithium",
    "crates/lamport_ots",
    "crates/winternitz_ots",
    "crates/lms",
    "crates/mayo",
    "crates/hss",
    "crates/xmss",
    "crates/xmssmt",
    "crates/sphincs_plus",
    "crates/cross",
    "crates/sqisign",
    "crates/leansig",
    "crates/less",
    "crates/bench_runner",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.92"
