[package]
name = "xmss-bench"
version.workspace = true
edition.workspace = true

[dependencies]
xmss = "0.1.0-pre.0"
rand = "0.10"
pq_bench = { path = "../pq_bench" }

[dev-dependencies]
divan = "0.1"

[[bin]]
name = "xmss"
path = "src/main.rs"

[[bin]]
name = "xmss_bench"
path = "src/bin/xmss_bench.rs"

[[bench]]
name = "xmss_divan"
harness = false
